apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: ml
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: mlflow-tls
spec:
  selector:
    name: mlflow-server
  ports:
    - name: https
      port: 8443
      targetPort: 8443
