apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-data
  namespace: ml
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mcp-pf-fs-storageclass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: ml
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      securityContext:
        fsGroup: 26
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: pgsql-data
      containers:
        - name: postgresql
          image: "registry.redhat.io/rhel8/postgresql-13:1-101"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_USER
              value: "admin"
            - name: POSTGRESQL_PASSWORD
              value: "<pwd>"
            - name: POSTGRESQL_DATABASE
              value: "<db-name>"
            - name: PGDATA
              value: /var/lib/pgsql/data/userdata   # 💥 FIX CRITICO
          ports:
            - containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "500m"
              memory: 1Gi
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
