apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow
  namespace: ml
spec:
  to:
    kind: Service
    name: mlflow-server
  tls:
    termination: reencrypt
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      {{ automatically provided by OpenShift }}
      -----END CERTIFICATE-----
